// Generated by CoffeeScript 1.7.1
(function() {
  var Clock, ViewPort, drawCircle,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ViewPort = require('./ViewPort');

  drawCircle = function(c2d, x, y, rad) {
    c2d.beginPath();
    c2d.arc(x, y, rad, 0, 2 * Math.PI, false);
    c2d.stroke();
    return c2d.fill();
  };

  Clock = (function(_super) {
    __extends(Clock, _super);

    function Clock() {
      var angle, time;
      this.angles = (function() {
        var _i, _results;
        _results = [];
        for (time = _i = 0; _i < 60; time = ++_i) {
          angle = 3 * Math.PI / 2 + 2 * Math.PI * time / 60;
          _results.push([Math.cos(angle), Math.sin(angle)]);
        }
        return _results;
      })();
    }

    Clock.prototype.renderComponent = function(c2d) {
      var h, hr, min, now, sec, w, _ref;
      _ref = this.size(), w = _ref[0], h = _ref[1];
      c2d.save();
      c2d.translate(w / 2, h / 2);
      c2d.fillStyle = '#FFFFFF';
      drawCircle(c2d, 0, 0, w / 2);
      now = new Date();
      hr = now.getHours();
      min = now.getMinutes();
      sec = now.getSeconds();
      c2d.strokeStyle = '#000000';
      c2d.fillStyle = '#FF0000';
      drawCircle(c2d, this.angles[hr * 5][0] * w / 2, this.angles[hr * 5][1] * h / 2, 100);
      c2d.fillStyle = '#00FF00';
      drawCircle(c2d, this.angles[min][0] * w / 2, this.angles[min][1] * h / 2, 50);
      c2d.fillStyle = '#0000FF';
      drawCircle(c2d, this.angles[sec][0] * w / 2, this.angles[sec][1] * h / 2, 25);
      return c2d.restore();
    };

    return Clock;

  })(ViewPort);

  module.exports = Clock;

}).call(this);
