// Generated by CoffeeScript 1.7.1
(function() {
  var Canvas, canvas, ctx, eu, render;

  eu = require('./util');

  Canvas = require('../lib/canvas');

  canvas = new Canvas(500, 500);

  ctx = canvas.getContext('2d');

var loc = 0;
  render = function() {
    ctx.fillStyle = "#FF0000";
    return ctx.fillRect(++loc, 200, 50, 50);
  };

setInterval(function(){
  requestAnimationFrame(render);
}, 1000/30);

  eu.waitForInput();

}).call(this);
