// Generated by CoffeeScript 1.7.1
(function() {
  var Canvas, Clock, a, b, c, canvas, ctx, eu, _i, _len;

  eu = require('./util');

  Canvas = require('../lib/canvas');

  Clock = require('./clock');

  canvas = new Canvas(500, 500);

  ctx = canvas.getContext('2d');

  ctx.translate(50, 50);

  c = new Clock();

  console.log(c);

  for (b = _i = 0, _len = c.length; _i < _len; b = ++_i) {
    a = c[b];
    console.log("" + a + ":  " + b);
  }

  c.size(500, 500);

  c.needsRender(true);

  eu.animate(function() {
    return c.render(ctx);
  });

  process.stdin.pause();

  eu.waitForInput();

}).call(this);
