// Generated by CoffeeScript 1.7.1
(function() {
  var ViewPort;

  ViewPort = (function() {
    function ViewPort() {
      this.needsRender(true);
      this.__size = [0, 0];
    }

    ViewPort.prototype.needsRender = function(val) {
      if (val != null) {
        this.__needsRender = val;
      }
      return this.__needsRender;
    };

    ViewPort.prototype.size = function(w, h) {
      if ((w != null) && (h != null)) {
        this.__size = [w, h];
        this.needsRender(true);
      }
      return this.__size;
    };

    ViewPort.prototype.render = function(context) {
      return this.renderComponent.call(this, context);
    };

    ViewPort.prototype.renderComponent = function(c2d) {
      var h, w, _ref;
      _ref = this.size(), w = _ref[0], h = _ref[1];
      c2d.fillStyle = '#FFFFFF';
      c2d.fillRect(0, 0, w, h);
      c2d.fillStyle = '#000000';
      return c2d.drawString("Not Implemented", w / 2, h / 2);
    };

    return ViewPort;

  })();

  module.exports = ViewPort;

}).call(this);
