// Generated by CoffeeScript 1.6.3
(function() {
  var ViewPort;

  ViewPort = (function() {
    function ViewPort(renderComponent) {
      this.renderComponent = renderComponent;
      this.__buffer = null;
    }

    ViewPort.prototype.needsRender = function(val) {
      if (val != null) {
        this.__needsRender = val;
      }
      return this.__needsRender;
    };

    ViewPort.prototype.size = function(w, h) {
      if ((w != null) && (h != null)) {
        this.__size = [w, h];
        this.needsRender(true);
      }
      return this.__size;
    };

    ViewPort.prototype.render = function(context) {
      if (this.__needsRender) {
        return renderComponent.call(this, context);
      }
    };

    return ViewPort;

  })();

}).call(this);
